# dataflex-gateway-alpha.yml
# https://cloud.spring.io/spring-cloud-gateway/reference/html/
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 1000ms
      routes:
        - id: member-service
          uri: http://localhost:8080
#          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/dataflex/member/**
          filters:
            - RewritePath=/api(?<path>.*),$\{path}
            - AddRequestHeader=X-member-Header, member-service-header
            - name: Hystrix
              args:
                name: hystrix
                fallbackUri: forward:/fallback/member
        - id: contents-service
          uri: http://localhost:8081
#          uri: lb://CONTENTS-SERVICE
          predicates:
            - Path=/api/dataflex/pay/**
          filters:
            - RewritePath=/api(?<path>.*),$\{path}
            - AddRequestHeader=X-pay-Header, pay-service-header
            - name: Hystrix
              args:
                name: hystrix
                fallbackUri: forward:/fallback/contents
        - id: dataflex-worker-dbms
          uri: http://localhost:8082
#          uri: lb://DATAFLEX-WORKER-DBMS
          predicates:
            - Path=/api/dataflex/v1/dbms/**
          filters:
            - RewritePath=/api(?<path01>.*)/v1(?<path02>.*),$\{path01}$\{path02}
            - name: Hystrix
              args:
                name: hystrix
                fallbackUri: forward:/fallback/websocket

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: hystrix.stream, routes, info, refresh, shutdown
